import { ACTIVE_DATASET } from '../generator.config';
import { DeterministicRandom } from '../deterministic-random';
import { generateReferenceData } from '../reference-data/reference-data';
export interface MarketingCampaign { campaignId: number; campaignName: string; channel: string; targetSegmentId: number | null; targetRegionId: number | null; startDate: string; endDate: string; budget: number }
export interface CampaignSpend { campaignSpendId: number; campaignId: number; spendDate: string; amount: number }
export interface CampaignData { campaigns: MarketingCampaign[]; campaignSpend: CampaignSpend[] }
const channels = ['email', 'paid_social', 'search', 'display']; const names = ['Monsoon Discovery', 'Festival Value', 'Everyday Essentials', 'Spring Refresh', 'Weekend Spotlight'];
const day = 86400000; const date = (value: number) => new Date(value).toISOString().slice(0, 10); const stamp = (value: string) => Date.parse(`${value}T00:00:00Z`);
function spend(campaigns: MarketingCampaign[]): CampaignSpend[] { let id = 1; return campaigns.flatMap((campaign) => { const start = stamp(campaign.startDate); const days = Math.floor((stamp(campaign.endDate) - start) / day) + 1; const cents = Math.round(campaign.budget * 100); const daily = Math.floor(cents / days); return Array.from({ length: days }, (_, index) => ({ campaignSpendId: id++, campaignId: campaign.campaignId, spendDate: date(start + index * day), amount: Number(((index === days - 1 ? cents - daily * (days - 1) : daily) / 100).toFixed(2)) })); }); }
export function generateCampaignData(seed: number = ACTIVE_DATASET.seed): CampaignData { const random = new DeterministicRandom(seed); const ref = generateReferenceData(seed); const start = stamp(ACTIVE_DATASET.datasetStartDate); const latest = stamp(ACTIVE_DATASET.asOfDate); const campaigns: MarketingCampaign[] = [{ campaignId: 1, campaignName: 'Summer Loyalty Push', channel: 'email', targetSegmentId: ref.customerSegments.find((x) => x.segmentName === 'Loyal')!.segmentId, targetRegionId: ref.regions.find((x) => x.regionName === 'South')!.regionId, startDate: '2025-05-15', endDate: '2025-07-31', budget: 12000 }]; for (let i = 1; i < ACTIVE_DATASET.campaigns; i += 1) { const campaignStart = start + random.nextInt(0, Math.floor((latest - start) / day) - 45) * day; const duration = random.nextInt(14, 45); campaigns.push({ campaignId: i + 1, campaignName: `${names[random.nextInt(0, names.length - 1)]} ${i}`, channel: channels[random.nextInt(0, channels.length - 1)], targetSegmentId: random.nextInt(0, 3) === 0 ? null : ref.customerSegments[random.nextInt(0, 3)].segmentId, targetRegionId: random.nextInt(0, 3) === 0 ? null : ref.regions[random.nextInt(0, 4)].regionId, startDate: date(campaignStart), endDate: date(campaignStart + duration * day), budget: Number((random.nextInt(500000, 2000000) / 100).toFixed(2)) }); } return { campaigns, campaignSpend: spend(campaigns) }; }
